services:
  redis:
    image: redis:latest
    container_name: funda-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--notify-keyspace-events", "ExgK"]
    restart: unless-stopped

  funda.api:
    image: funda.api
    build:
      context: .
      dockerfile: src/Host/Funda.Api/Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "12001:8080"

  funda.feeds.workerservice:
    image: funda.feeds.workerservice
    build:
      context: .
      dockerfile: src/Host/Funda.Feeds.WorkerService/Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  redis-data:
